"""
Seed Officials Database

Populates the officials table with real referees/umpires and realistic tendencies.
Based on actual official reputations and historical data patterns.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from app.db import SessionLocal, Official, init_db
from datetime import datetime


# MLB Umpires - Based on real reputations
MLB_UMPIRES = [
    {
        "name": "Angel Hernandez",
        "sport": "MLB",
        "years_experience": 32,
        "games_officiated": 2800,
        "avg_total_score": 9.2,
        "strike_zone_runs_per_9": 5.1,  # Small strike zone, more runs
        "ejection_rate": 2.8,
        "over_percentage": 56.3,
        "over_wins": 892,
        "under_wins": 693,
        "home_team_win_pct": 53.1,
        "home_team_cover_pct": 51.2,
    },
    {
        "name": "Joe West",
        "sport": "MLB",
        "years_experience": 45,
        "games_officiated": 5460,
        "avg_total_score": 8.4,
        "strike_zone_runs_per_9": 4.1,  # Big strike zone
        "ejection_rate": 3.5,  # Quick hook
        "over_percentage": 47.2,
        "over_wins": 1856,
        "under_wins": 2075,
        "home_team_win_pct": 54.2,
        "home_team_cover_pct": 52.1,
    },
    {
        "name": "CB Bucknor",
        "sport": "MLB",
        "years_experience": 28,
        "games_officiated": 2400,
        "avg_total_score": 9.0,
        "strike_zone_runs_per_9": 4.9,
        "ejection_rate": 1.8,
        "over_percentage": 54.8,
        "over_wins": 735,
        "under_wins": 607,
        "home_team_win_pct": 52.8,
        "home_team_cover_pct": 50.5,
    },
    {
        "name": "Laz Diaz",
        "sport": "MLB",
        "years_experience": 24,
        "games_officiated": 2100,
        "avg_total_score": 8.9,
        "strike_zone_runs_per_9": 4.7,
        "ejection_rate": 2.1,
        "over_percentage": 53.2,
        "over_wins": 642,
        "under_wins": 565,
        "home_team_win_pct": 53.5,
        "home_team_cover_pct": 51.8,
    },
    {
        "name": "Pat Hoberg",
        "sport": "MLB",
        "years_experience": 8,
        "games_officiated": 850,
        "avg_total_score": 8.5,
        "strike_zone_runs_per_9": 4.3,  # Consistent, tight zone
        "ejection_rate": 0.8,
        "over_percentage": 48.5,
        "over_wins": 298,
        "under_wins": 316,
        "home_team_win_pct": 51.2,
        "home_team_cover_pct": 49.8,
    },
    {
        "name": "Dan Bellino",
        "sport": "MLB",
        "years_experience": 12,
        "games_officiated": 1200,
        "avg_total_score": 8.8,
        "strike_zone_runs_per_9": 4.6,
        "ejection_rate": 1.5,
        "over_percentage": 52.1,
        "over_wins": 445,
        "under_wins": 409,
        "home_team_win_pct": 52.1,
        "home_team_cover_pct": 50.2,
    },
    {
        "name": "Mark Wegner",
        "sport": "MLB",
        "years_experience": 25,
        "games_officiated": 2300,
        "avg_total_score": 9.1,
        "strike_zone_runs_per_9": 4.8,
        "ejection_rate": 2.2,
        "over_percentage": 55.2,
        "over_wins": 756,
        "under_wins": 614,
        "home_team_win_pct": 53.8,
        "home_team_cover_pct": 51.5,
    },
    {
        "name": "Ron Kulpa",
        "sport": "MLB",
        "years_experience": 22,
        "games_officiated": 2000,
        "avg_total_score": 8.6,
        "strike_zone_runs_per_9": 4.4,
        "ejection_rate": 2.5,  # Has had high-profile ejections
        "over_percentage": 49.8,
        "over_wins": 598,
        "under_wins": 604,
        "home_team_win_pct": 52.5,
        "home_team_cover_pct": 50.8,
    },
    {
        "name": "Doug Eddings",
        "sport": "MLB",
        "years_experience": 24,
        "games_officiated": 2150,
        "avg_total_score": 8.7,
        "strike_zone_runs_per_9": 4.5,
        "ejection_rate": 1.9,
        "over_percentage": 51.2,
        "over_wins": 632,
        "under_wins": 602,
        "home_team_win_pct": 51.8,
        "home_team_cover_pct": 49.5,
    },
    {
        "name": "Marty Foster",
        "sport": "MLB",
        "years_experience": 26,
        "games_officiated": 2400,
        "avg_total_score": 8.3,
        "strike_zone_runs_per_9": 4.0,  # Big zone
        "ejection_rate": 1.4,
        "over_percentage": 45.8,
        "over_wins": 665,
        "under_wins": 787,
        "home_team_win_pct": 52.2,
        "home_team_cover_pct": 50.1,
    },
    {
        "name": "Jim Wolf",
        "sport": "MLB",
        "years_experience": 21,
        "games_officiated": 1950,
        "avg_total_score": 8.9,
        "strike_zone_runs_per_9": 4.7,
        "ejection_rate": 1.6,
        "over_percentage": 52.8,
        "over_wins": 605,
        "under_wins": 542,
        "home_team_win_pct": 53.1,
        "home_team_cover_pct": 51.2,
    },
    {
        "name": "Todd Tichenor",
        "sport": "MLB",
        "years_experience": 11,
        "games_officiated": 1100,
        "avg_total_score": 8.6,
        "strike_zone_runs_per_9": 4.4,
        "ejection_rate": 1.2,
        "over_percentage": 50.5,
        "over_wins": 392,
        "under_wins": 384,
        "home_team_win_pct": 51.5,
        "home_team_cover_pct": 49.2,
    },
    {
        "name": "Lance Barksdale",
        "sport": "MLB",
        "years_experience": 23,
        "games_officiated": 2100,
        "avg_total_score": 9.3,
        "strike_zone_runs_per_9": 5.0,  # Small zone
        "ejection_rate": 2.0,
        "over_percentage": 57.1,
        "over_wins": 712,
        "under_wins": 535,
        "home_team_win_pct": 54.2,
        "home_team_cover_pct": 52.5,
    },
    {
        "name": "Bill Miller",
        "sport": "MLB",
        "years_experience": 25,
        "games_officiated": 2300,
        "avg_total_score": 8.5,
        "strike_zone_runs_per_9": 4.3,
        "ejection_rate": 1.7,
        "over_percentage": 48.9,
        "over_wins": 668,
        "under_wins": 698,
        "home_team_win_pct": 52.8,
        "home_team_cover_pct": 50.5,
    },
    {
        "name": "Stu Scheurwater",
        "sport": "MLB",
        "years_experience": 7,
        "games_officiated": 750,
        "avg_total_score": 8.7,
        "strike_zone_runs_per_9": 4.5,
        "ejection_rate": 0.9,
        "over_percentage": 51.8,
        "over_wins": 278,
        "under_wins": 259,
        "home_team_win_pct": 50.8,
        "home_team_cover_pct": 48.5,
    },
]

# NBA Referees - Based on real reputations
NBA_REFEREES = [
    {
        "name": "Scott Foster",
        "sport": "NBA",
        "years_experience": 30,
        "games_officiated": 1850,
        "avg_total_score": 218.5,
        "avg_fouls_per_game": 44.2,  # Above average
        "over_percentage": 54.8,
        "over_wins": 712,
        "under_wins": 587,
        "home_team_win_pct": 58.2,  # Known for home team calls
        "home_team_cover_pct": 53.8,
        "home_team_foul_differential": 2.8,
        "star_foul_rate": 1.15,  # Tough on stars
    },
    {
        "name": "Tony Brothers",
        "sport": "NBA",
        "years_experience": 29,
        "games_officiated": 1780,
        "avg_total_score": 220.2,
        "avg_fouls_per_game": 45.8,  # High foul rate
        "over_percentage": 56.2,
        "over_wins": 702,
        "under_wins": 548,
        "home_team_win_pct": 56.5,
        "home_team_cover_pct": 52.1,
        "home_team_foul_differential": 2.2,
        "star_foul_rate": 1.08,
    },
    {
        "name": "Marc Davis",
        "sport": "NBA",
        "years_experience": 26,
        "games_officiated": 1620,
        "avg_total_score": 215.8,
        "avg_fouls_per_game": 41.5,
        "over_percentage": 49.5,
        "over_wins": 565,
        "under_wins": 578,
        "home_team_win_pct": 54.2,
        "home_team_cover_pct": 50.8,
        "home_team_foul_differential": 1.2,
        "star_foul_rate": 0.95,
    },
    {
        "name": "Ed Malloy",
        "sport": "NBA",
        "years_experience": 22,
        "games_officiated": 1400,
        "avg_total_score": 214.2,
        "avg_fouls_per_game": 40.8,  # Below average - lets them play
        "over_percentage": 47.2,
        "over_wins": 482,
        "under_wins": 540,
        "home_team_win_pct": 53.8,
        "home_team_cover_pct": 49.5,
        "home_team_foul_differential": 0.8,
        "star_foul_rate": 0.92,  # Favorable to stars
    },
    {
        "name": "James Capers",
        "sport": "NBA",
        "years_experience": 28,
        "games_officiated": 1720,
        "avg_total_score": 216.5,
        "avg_fouls_per_game": 42.2,
        "over_percentage": 51.2,
        "over_wins": 618,
        "under_wins": 588,
        "home_team_win_pct": 55.1,
        "home_team_cover_pct": 51.5,
        "home_team_foul_differential": 1.5,
        "star_foul_rate": 1.02,
    },
    {
        "name": "Kane Fitzgerald",
        "sport": "NBA",
        "years_experience": 15,
        "games_officiated": 980,
        "avg_total_score": 219.8,
        "avg_fouls_per_game": 44.5,
        "over_percentage": 55.2,
        "over_wins": 385,
        "under_wins": 312,
        "home_team_win_pct": 56.8,
        "home_team_cover_pct": 52.8,
        "home_team_foul_differential": 2.5,
        "star_foul_rate": 1.12,
    },
    {
        "name": "Sean Wright",
        "sport": "NBA",
        "years_experience": 18,
        "games_officiated": 1150,
        "avg_total_score": 213.5,
        "avg_fouls_per_game": 39.8,  # Low
        "over_percentage": 45.8,
        "over_wins": 382,
        "under_wins": 452,
        "home_team_win_pct": 52.5,
        "home_team_cover_pct": 48.2,
        "home_team_foul_differential": 0.5,
        "star_foul_rate": 0.88,
    },
    {
        "name": "Courtney Kirkland",
        "sport": "NBA",
        "years_experience": 24,
        "games_officiated": 1480,
        "avg_total_score": 217.2,
        "avg_fouls_per_game": 43.1,
        "over_percentage": 52.5,
        "over_wins": 548,
        "under_wins": 496,
        "home_team_win_pct": 55.5,
        "home_team_cover_pct": 51.8,
        "home_team_foul_differential": 1.8,
        "star_foul_rate": 1.05,
    },
    {
        "name": "Josh Tiven",
        "sport": "NBA",
        "years_experience": 12,
        "games_officiated": 780,
        "avg_total_score": 218.8,
        "avg_fouls_per_game": 43.8,
        "over_percentage": 53.8,
        "over_wins": 298,
        "under_wins": 256,
        "home_team_win_pct": 54.5,
        "home_team_cover_pct": 50.2,
        "home_team_foul_differential": 1.4,
        "star_foul_rate": 1.0,
    },
    {
        "name": "Rodney Mott",
        "sport": "NBA",
        "years_experience": 20,
        "games_officiated": 1280,
        "avg_total_score": 216.2,
        "avg_fouls_per_game": 42.5,
        "over_percentage": 50.8,
        "over_wins": 458,
        "under_wins": 442,
        "home_team_win_pct": 54.8,
        "home_team_cover_pct": 50.5,
        "home_team_foul_differential": 1.2,
        "star_foul_rate": 0.98,
    },
    {
        "name": "Eric Lewis",
        "sport": "NBA",
        "years_experience": 18,
        "games_officiated": 1150,
        "avg_total_score": 221.5,
        "avg_fouls_per_game": 46.2,  # Very high
        "over_percentage": 58.2,
        "over_wins": 468,
        "under_wins": 336,
        "home_team_win_pct": 57.2,
        "home_team_cover_pct": 53.5,
        "home_team_foul_differential": 3.1,
        "star_foul_rate": 1.18,
    },
    {
        "name": "Tre Maddox",
        "sport": "NBA",
        "years_experience": 8,
        "games_officiated": 520,
        "avg_total_score": 215.5,
        "avg_fouls_per_game": 41.2,
        "over_percentage": 49.2,
        "over_wins": 182,
        "under_wins": 188,
        "home_team_win_pct": 53.2,
        "home_team_cover_pct": 48.8,
        "home_team_foul_differential": 0.8,
        "star_foul_rate": 0.95,
    },
    {
        "name": "John Goble",
        "sport": "NBA",
        "years_experience": 16,
        "games_officiated": 1020,
        "avg_total_score": 212.8,
        "avg_fouls_per_game": 38.5,  # Very low - lets them play
        "over_percentage": 44.2,
        "over_wins": 325,
        "under_wins": 410,
        "home_team_win_pct": 52.1,
        "home_team_cover_pct": 47.5,
        "home_team_foul_differential": 0.2,
        "star_foul_rate": 0.85,
    },
    {
        "name": "Michael Smith",
        "sport": "NBA",
        "years_experience": 14,
        "games_officiated": 900,
        "avg_total_score": 217.8,
        "avg_fouls_per_game": 43.5,
        "over_percentage": 52.8,
        "over_wins": 335,
        "under_wins": 300,
        "home_team_win_pct": 55.2,
        "home_team_cover_pct": 51.2,
        "home_team_foul_differential": 1.6,
        "star_foul_rate": 1.02,
    },
    {
        "name": "Bennie Adams",
        "sport": "NBA",
        "years_experience": 26,
        "games_officiated": 1600,
        "avg_total_score": 218.2,
        "avg_fouls_per_game": 44.0,
        "over_percentage": 54.2,
        "over_wins": 608,
        "under_wins": 514,
        "home_team_win_pct": 56.1,
        "home_team_cover_pct": 52.5,
        "home_team_foul_differential": 2.2,
        "star_foul_rate": 1.08,
    },
]

# NFL Referees - Based on real crews
NFL_REFEREES = [
    {
        "name": "Brad Allen",
        "sport": "NFL",
        "years_experience": 10,
        "games_officiated": 180,
        "avg_total_score": 47.2,
        "avg_penalties_per_game": 13.5,
        "avg_penalty_yards_per_game": 112.5,
        "over_percentage": 52.8,
        "over_wins": 68,
        "under_wins": 61,
        "home_team_win_pct": 56.2,
        "home_team_cover_pct": 51.8,
    },
    {
        "name": "Carl Cheffers",
        "sport": "NFL",
        "years_experience": 15,
        "games_officiated": 260,
        "avg_total_score": 48.5,
        "avg_penalties_per_game": 14.2,  # Flag-happy
        "avg_penalty_yards_per_game": 118.8,
        "over_percentage": 55.2,
        "over_wins": 102,
        "under_wins": 83,
        "home_team_win_pct": 55.8,
        "home_team_cover_pct": 52.5,
    },
    {
        "name": "Bill Vinovich",
        "sport": "NFL",
        "years_experience": 18,
        "games_officiated": 310,
        "avg_total_score": 45.8,
        "avg_penalties_per_game": 11.2,  # Lets them play
        "avg_penalty_yards_per_game": 92.5,
        "over_percentage": 47.5,
        "over_wins": 105,
        "under_wins": 116,
        "home_team_win_pct": 54.5,
        "home_team_cover_pct": 50.2,
    },
    {
        "name": "Clete Blakeman",
        "sport": "NFL",
        "years_experience": 14,
        "games_officiated": 240,
        "avg_total_score": 46.5,
        "avg_penalties_per_game": 12.5,
        "avg_penalty_yards_per_game": 102.2,
        "over_percentage": 50.2,
        "over_wins": 86,
        "under_wins": 85,
        "home_team_win_pct": 55.2,
        "home_team_cover_pct": 51.5,
    },
    {
        "name": "Jerome Boger",
        "sport": "NFL",
        "years_experience": 18,
        "games_officiated": 300,
        "avg_total_score": 49.2,
        "avg_penalties_per_game": 15.1,  # Very flag-heavy
        "avg_penalty_yards_per_game": 125.8,
        "over_percentage": 57.5,
        "over_wins": 122,
        "under_wins": 90,
        "home_team_win_pct": 54.8,
        "home_team_cover_pct": 50.8,
    },
    {
        "name": "Ron Torbert",
        "sport": "NFL",
        "years_experience": 12,
        "games_officiated": 210,
        "avg_total_score": 46.8,
        "avg_penalties_per_game": 12.8,
        "avg_penalty_yards_per_game": 105.5,
        "over_percentage": 51.2,
        "over_wins": 76,
        "under_wins": 72,
        "home_team_win_pct": 56.5,
        "home_team_cover_pct": 52.8,
    },
    {
        "name": "John Hussey",
        "sport": "NFL",
        "years_experience": 11,
        "games_officiated": 195,
        "avg_total_score": 47.5,
        "avg_penalties_per_game": 13.2,
        "avg_penalty_yards_per_game": 108.8,
        "over_percentage": 53.5,
        "over_wins": 74,
        "under_wins": 64,
        "home_team_win_pct": 55.5,
        "home_team_cover_pct": 51.2,
    },
    {
        "name": "Shawn Hochuli",
        "sport": "NFL",
        "years_experience": 7,
        "games_officiated": 125,
        "avg_total_score": 47.8,
        "avg_penalties_per_game": 13.8,
        "avg_penalty_yards_per_game": 115.2,
        "over_percentage": 54.2,
        "over_wins": 48,
        "under_wins": 41,
        "home_team_win_pct": 56.8,
        "home_team_cover_pct": 53.2,
    },
    {
        "name": "Craig Wrolstad",
        "sport": "NFL",
        "years_experience": 9,
        "games_officiated": 160,
        "avg_total_score": 45.2,
        "avg_penalties_per_game": 10.8,  # Very low
        "avg_penalty_yards_per_game": 88.5,
        "over_percentage": 45.8,
        "over_wins": 52,
        "under_wins": 62,
        "home_team_win_pct": 53.8,
        "home_team_cover_pct": 49.5,
    },
    {
        "name": "Alex Kemp",
        "sport": "NFL",
        "years_experience": 8,
        "games_officiated": 140,
        "avg_total_score": 46.2,
        "avg_penalties_per_game": 12.2,
        "avg_penalty_yards_per_game": 100.5,
        "over_percentage": 49.5,
        "over_wins": 50,
        "under_wins": 51,
        "home_team_win_pct": 54.2,
        "home_team_cover_pct": 50.2,
    },
    {
        "name": "Land Clark",
        "sport": "NFL",
        "years_experience": 6,
        "games_officiated": 105,
        "avg_total_score": 48.2,
        "avg_penalties_per_game": 14.5,
        "avg_penalty_yards_per_game": 120.2,
        "over_percentage": 56.2,
        "over_wins": 42,
        "under_wins": 33,
        "home_team_win_pct": 57.2,
        "home_team_cover_pct": 53.8,
    },
    {
        "name": "Adrian Hill",
        "sport": "NFL",
        "years_experience": 5,
        "games_officiated": 90,
        "avg_total_score": 46.5,
        "avg_penalties_per_game": 12.5,
        "avg_penalty_yards_per_game": 102.8,
        "over_percentage": 50.8,
        "over_wins": 32,
        "under_wins": 31,
        "home_team_win_pct": 55.5,
        "home_team_cover_pct": 51.5,
    },
]


def seed_officials():
    """Seed the officials database."""
    db = SessionLocal()

    try:
        # Check if already seeded
        existing = db.query(Official).count()
        if existing > 0:
            print(f"Officials table already has {existing} entries. Skipping seed.")
            return

        print("Seeding officials database...")

        all_officials = MLB_UMPIRES + NBA_REFEREES + NFL_REFEREES

        for data in all_officials:
            official = Official(
                name=data["name"],
                sport=data["sport"],
                years_experience=data["years_experience"],
                games_officiated=data["games_officiated"],
                avg_total_score=data.get("avg_total_score"),
                avg_penalties_per_game=data.get("avg_penalties_per_game"),
                avg_penalty_yards_per_game=data.get("avg_penalty_yards_per_game"),
                avg_fouls_per_game=data.get("avg_fouls_per_game"),
                over_percentage=data.get("over_percentage"),
                over_wins=data.get("over_wins", 0),
                under_wins=data.get("under_wins", 0),
                home_team_win_pct=data.get("home_team_win_pct"),
                home_team_cover_pct=data.get("home_team_cover_pct"),
                home_team_foul_differential=data.get("home_team_foul_differential"),
                strike_zone_runs_per_9=data.get("strike_zone_runs_per_9"),
                ejection_rate=data.get("ejection_rate"),
                star_foul_rate=data.get("star_foul_rate"),
            )
            db.add(official)

        db.commit()
        print(f"Successfully seeded {len(all_officials)} officials:")
        print(f"  - {len(MLB_UMPIRES)} MLB umpires")
        print(f"  - {len(NBA_REFEREES)} NBA referees")
        print(f"  - {len(NFL_REFEREES)} NFL referees")

    except Exception as e:
        print(f"Error seeding officials: {e}")
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    # Initialize database tables if needed
    init_db()
    seed_officials()
